#  - Disables version-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates for npm dependencies, keep only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "daily"
    # Disable version updates for npm dependencies, keep only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable version updates for gemfile dependencies, keep only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: "bundler"
    directory: "/example"
    schedule:
      interval: "weekly"
    # Disable version updates for gemfile dependencies, keep only security updates
    open-pull-requests-limit: 0
